faq/urls.py
from django.urls import path
from .views import CategoryListView

urlpatterns = [
    path("", CategoryListView.as_view(), name="category-list")
]

metref/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("studies/", include("studies.urls")),
    path("faq/", include("faq.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"), 
    path("select2/", include("django_select2.urls", namespace='default')),
    path('tinymce/',include('tinymce.urls')),
]

faq/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=200)
    order = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return f"{self.title+" ("+str(self.order)+")"}"

class Entry(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null = True)
    text = models.TextField(default="")
    order = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return f"{self.title+" ("+str(self.order)+")"}"

faq/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Entry, Category

# Create your views here.

class CategoryListView(ListView):
    model = Category
    context_object_name = 'category_list'

templates/faq/category_list.html
{% extends "base.html" %}
{% block title %}metRef{% endblock %}
{% block content %}
<h1>FAQ</h1>
<div class="accordion accordion-flush" id="accordionFaq">
    {% for category in category_list|dictsortreversed:"order" %}
    <div class="accordion-item">
        <h2 class="accordion-header" id="heading{{category.id}}">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{category.id}}" aria-expanded="false" aria-controls="flush-collapse{{category.id}}">
                {{ category.title }}
            </button>
        </h2>
        <div id="flush-collapse{{category.id}}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{category.id}}" data-bs-parent="#accordionFaq">
            <div class="accordion-body">
                {% for entry in category.entry_set.all|dictsortreversed:"order" %}
                    <div class="entry_title_faq">
                    {{ entry.title }}    
                    </div>
                    <div class="entry_text_faq">
                    {{ entry.text|safe }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>    
    {% endfor %}
</div>
{% endblock %}