faq/urls.py
from django.urls import path
from .views import CategoryListView

urlpatterns = [
    path("", CategoryListView.as_view(), name="category-list")
]

metref/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("studies/", include("studies.urls")),
    path("faq/", include("faq.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"), 
    path("select2/", include("django_select2.urls", namespace='default')),
    path('tinymce/',include('tinymce.urls')),
]

studies/models.py
from django.db import models
from taxonomy.models import Version, Taxon, Genome
from django.contrib.auth.models import User
from django.urls import reverse
from .tasks import taxon_to_list
from django.db import transaction
from django.db.models.signals import m2m_changed
from django.dispatch import receiver
from metref import settings
# Create your models here.

class Study(models.Model):
    title = models.CharField(max_length=200,default='')
    version = models.ForeignKey(Version, on_delete=models.CASCADE)
    taxon = models.ManyToManyField(Taxon)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def get_absolute_url(self):
        return reverse("study-detail", kwargs={"pk": self.pk})
    
    def save(self, *args, **kwargs):
        super(Study, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.title}"

@receiver(m2m_changed, sender=Study.taxon.through)
def signal(sender, instance, action, reverse, pk_set, **kwargs):
    if action == "post_remove":
        for tax_id in pk_set :
            GenomeList.objects.filter(study=instance, taxon=tax_id).delete()
        
    elif action == "post_add":
        previous_lists = list(GenomeList.objects.filter(study=instance.id).values_list('taxon', flat=True))
        print(previous_lists)
        for taxon in instance.taxon.all():
            print(taxon.id)
            if taxon.id not in previous_lists:
                gl= GenomeList()
                gl.study = instance
                gl.taxon = taxon
                gl.save()
                taxon_to_list.delay(taxon.id, instance.version.id, instance.id, gl.id)

class GenomeList(models.Model):
    study = models.ForeignKey(Study, on_delete=models.CASCADE)
    taxon = models.ForeignKey(Taxon, on_delete=models.CASCADE)
    genomes = models.ManyToManyField(Genome)
    status = models.PositiveSmallIntegerField(default=0)

       

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  {% load static %}
  <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
  <meta name="title" content="metRef">
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <script
  src="https://code.jquery.com/jquery-3.7.1.min.js"
  integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
  crossorigin="anonymous"></script>
  <script src="../../static/django_select2/django_select2.js"></script>
</head>
<body>

<div class="container">
  <ul class="nav bg-info">
    <li class="nav-item">
      <a class="nav-link link-light" href="/">HOME</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="/studies">STUDIES</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="/faq">FAQ</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item" id ="logout_menu">
      <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit">LOGOUT</button>
    </form>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-link link-light" href="/accounts/login">LOGIN</a>
    </li>
    {% endif %}
  </ul>
  <div id="page_content">
  {% block content %}
  {% endblock %}
  </div>
</div>
</body>
<script src="{% static 'tinymce/js/prism.js' %}"></script>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}metRef{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<p>Welcome to metRef, {{ user.username }}!</p>
<p>Please, check the faq section if you have any question about the system.</p>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

templates/study_detail.html
{% extends "base.html" %}
{% block title %}metRef{% endblock %}
{% load static %}
{% block content %}
<h1>{{ object.title }}</h1>
{% if num_lists_inactive == 0 %}
<div id="buttons_study">
  <div class="button_study"><a href="{% url 'export-to-csv' object.id %}"><img src="{% static 'images/csv-file-icon.png' %}" title="export as csv" width="20px"/></a></div>
  {% if num_items >= 30 %}
    <div class="button_study"><a href="{% url 'download-analysis' object.id %}"><img src="{% static 'images/pdf-files-icon.png' %}" title="download analysis" width="20px"/></a></div>
  {% endif %}
</div>

<div class="accordion accordion-flush" id="accordionStudies">
{% for gl in object.genomelist_set.all %}
  <div class="accordion-item">
    {% with genomes=gl.genomes.all %} 
    <h2 class="accordion-header" id="heading{{gl.id}}">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{gl.id}}" aria-expanded="false" aria-controls="flush-collapse{{gl.id}}">
        {{gl.taxon.name}} ({{genomes|length}} genomes)
      </button>
    </h2>
    <div id="flush-collapse{{gl.id}}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{gl.id}}" data-bs-parent="#accordionStudies">
      <div class="accordion-body">
          {% for genome in genomes %}
          <li>{{ genome.accession }} - {{ genome.taxon.name }}</li>
          {% empty %}
          <li>Genomes not found.</li>
          {% endfor %}
      </div>
    </div>
    {% endwith %}
  </div>
  <!-- {{ gl.taxon.name }} #{{ gl.taxon.rank }} 
  {% with genomes=gl.genomes.all %}
    {% if genomes %}
      ({{ genomes|length }} genomes)
      {% for genome in genomes %}
        <li>{{ genome.accession }} ({{ genome.taxon.name }})</li>
      {% empty %}
      <li>Genomes not found.</li>
      {% endfor %}
    {% endif %}
  {% endwith %} -->
{% empty %}
<p>The list of genomes is being generated.</p>
{% endfor %}
</div>
{% else %}
<div>The list of genomes is being generated, please refresh in a few seconds.</div>
{% endif %}
{% endblock %}
  

templates/taxonomy_options.html
{% for tax in taxonomies %}
<option value="{{ tax.id }} ">{{ tax.name }}</option>"
{% endfor %}